{{- if .Values.applicationRepositories.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-repositories-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.applicationRepositories.repoURL | quote }}
    targetRevision: {{ .Values.applicationRepositories.targetRevision | quote }}
    path: crs
    directory:
      recurse: true
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
