apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taskapp-catalog
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/entr0pian/application-repositories.git"
              revision: main
              requeueAfterSeconds: 30
              files:
                - path: "components/*/environments/*.yaml"
          - clusters:
              selector:
                matchLabels:
                  environment: "{{`{{ .environment }}`}}"
  template:
    metadata:
      name: "{{`{{ index .path.segments 1 }}`}}-{{`{{ .environment }}`}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: "{{`{{ .source.repoURL }}`}}"
          targetRevision: "{{`{{ .source.targetRevision }}`}}"
          path: "{{`{{ .source.chartPath }}`}}"
          helm:
            releaseName: "{{`{{ index .path.segments 1 }}`}}"
            valueFiles:
              - "$values/components/{{`{{ index .path.segments 1 }}`}}/values/{{`{{ .environment }}`}}.yaml"
        - repoURL: "https://github.com/entr0pian/application-repositories.git"
          targetRevision: main
          ref: values
      destination:
        server: "{{`{{.server}}`}}"
        namespace: "{{`{{.namespace}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
