{{- if .Values.crossplaneProviderConfig.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-config-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: crossplane-provider-config
    helm:
      releaseName: crossplane-provider-config
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
