{{- if .Values.crossplaneCompositionsPackage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions-package-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.crossplaneCompositionsPackage.repoURL | quote }}
    targetRevision: {{ .Values.crossplaneCompositionsPackage.targetRevision | quote }}
    path: deploy
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
