apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://charts.crossplane.io/stable"
    chart: crossplane
    targetRevision: "1.19.1"
    helm:
      releaseName: crossplane
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
