apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp-database-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: database
    helm:
      releaseName: taskapp-database
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: default
  {{- include "taskapp.ignoreDifferences" (dict "kind" "StatefulSet") | nindent 2 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
