{{- if .Values.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://charts.external-secrets.io"
    chart: external-secrets
    targetRevision: "0.14.4"
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
