{{- if .Values.frontend.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp-frontend-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ .Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ .Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.frontend.repoURL | quote }}
    targetRevision: {{ .Values.frontend.targetRevision | quote }}
    path: chart
    helm:
      releaseName: taskapp-frontend
      parameters:
        - name: image.tag
          value: {{ .Values.frontend.image.tag | quote }}
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: default
  {{- include "taskapp.ignoreDifferences" (dict "kind" "Deployment") | nindent 2 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
