{{- if .Values.infra.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: taskapp-infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - merge:
              mergeKeys:
                - name
              generators:
                - git:
                    repoURL: {{ .Values.applicationRepositories.repoURL | quote }}
                    revision: {{ .Values.applicationRepositories.targetRevision | quote }}
                    files:
                      - path: "infra/*/*.yaml"
                - git:
                    repoURL: {{ .Values.applicationRepositories.repoURL | quote }}
                    revision: {{ .Values.applicationRepositories.targetRevision | quote }}
                    files:
                      - path: "values/*/*.yaml"
          - clusters:
              selector:
                matchLabels:
                  environment: "{{`{{ trimSuffix \".yaml\" .path.filename }}`}}"
  template:
    metadata:
      name: "{{`{{.name}}`}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{.wave}}`}}"
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "{{`{{ if .notify }}`}}{{ .Values.notifications.slack.channel }}{{`{{ end }}`}}"
        notifications.argoproj.io/subscribe.on-sync-failed.slack: "{{`{{ if .notify }}`}}{{ .Values.notifications.slack.channel }}{{`{{ end }}`}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: "{{`{{.repoURL}}`}}"
        targetRevision: "{{`{{.targetRevision}}`}}"
        chart: "{{`{{.chart}}`}}"
        path: "{{`{{.chartPath}}`}}"
        helm:
          releaseName: "{{`{{.path.basename}}`}}"
          values: "{{`{{.values}}`}}"
      destination:
        server: "{{`{{.server}}`}}"
        namespace: "{{`{{.namespace}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - "CreateNamespace={{`{{.createNamespace}}`}}"
          - "ServerSideApply={{`{{.serverSideApply}}`}}"
{{- end }}
