{{- if .Values.keda.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://kedacore.github.io/charts"
    chart: keda
    targetRevision: "2.16.1"
    helm:
      releaseName: keda
  destination:
    server: {{ .Values.destinationServer | quote }}
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
