{{- range $name, $repo := .Values.repositories }}
{{- if $repo.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}-{{ $.Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: {{ $.Values.notifications.slack.channel | quote }}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: {{ $.Values.notifications.slack.channel | quote }}
spec:
  project: default
  source:
    repoURL: {{ $repo.repoURL | quote }}
    targetRevision: {{ $repo.targetRevision | quote }}
    path: {{ $repo.chartPath | quote }}
    helm:
      releaseName: {{ $name }}
  destination:
    server: {{ $.Values.destinationServer | quote }}
    namespace: {{ $repo.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}
