env: dev
destinationServer: "https://172.19.0.2:6443"
crossplane:
  enabled: false
  secretPath: ""
crossplaneProviderConfig:
  enabled: false
operator:
  image:
    tag: ad520886b3e30842cda3b937163ccf2dd3301364
  credentialsSecretPath: taskapp/dev/backend-credentials
