env: prod
destinationServer: "https://172.19.0.4:6443"
crossplane:
  secretPath: taskapp/prod/crossplane-aws
backend:
  image:
    tag: "5005016e5bedda1b325f73da27410943e3c75a98"
frontend:
  image:
    tag: "d50b47cf5b502c2f6fe9b1bb642982021aa018fb"
operator:
  image:
    tag: "112108c11c371eb6a36c4cea1b1951624a874e40"
  credentialsSecretPath: taskapp/prod/backend-credentials
