env: management
externalSecrets:
  enabled: true
argocdWriteToken:
  secretPath: taskapp/platform/argocd-write-token
applicationRepositoryOperator:
  enabled: true
  image:
    tag: 2560bd73cfed12687bb48e502ab7f8f277a9384c
  requeueInterval: "30s"
applicationRepositories:
  enabled: true
kubePrometheusStack:
  enabled: false
keda:
  enabled: false
crossplane:
  enabled: false
crossplaneProviderConfig:
  enabled: false
crossplaneCompositions:
  enabled: false
atlasOperator:
  enabled: false
operator:
  enabled: false
platform:
  limitRange:
    enabled: false
  prometheusRules:
    enabled: false
  grafanaDashboard:
    enabled: false
repositories:
  frontend-test:
    enabled: false
    namespace: default
