env: management
externalSecrets:
  enabled: true
argocdWriteToken:
  secretPath: taskapp/platform/argocd-write-token
applicationRepositoryOperator:
  enabled: true
  image:
    tag: cf06d2ecb1575da61aa81144fb897431528ee75d
  requeueInterval: "30s"
kubePrometheusStack:
  enabled: false
keda:
  enabled: false
crossplane:
  enabled: false
crossplaneProviderConfig:
  enabled: false
crossplaneCompositions:
  enabled: false
atlasOperator:
  enabled: false
operator:
  enabled: false
platform:
  limitRange:
    enabled: false
  prometheusRules:
    enabled: false
  grafanaDashboard:
    enabled: false
repositories:
  frontend-test:
    enabled: true
    namespace: default
