applicationRepositories:
  repoURL: "https://github.com/entr0pian/application-repositories.git"
  targetRevision: main
catalog:
  enabled: false
infra:
  enabled: false
crossplaneCompositionsPackage:
  repoURL: "https://github.com/entr0pian/crossplane-compositions.git"
  targetRevision: main
notifications:
  slack:
    channel: deployments
